### ISSUE TITLE
Count Up Component 작성

### ISSUE THREAD

**Issue by Sweet-Pumpkin** [FC-Team15/react-countup#2]
## 목적
React 환경에서 카운트업 컴포넌트를 만들어 "+"버튼을 클릭하면 1만큼 숫자가 오르고, "-"버튼을 클릭하면 숫자가 1만큼 내려갈 수 있도록 한다.

## Task
- [x] + 버튼, - 버튼 생성
- [x] count 상태 관리
- [x] +버튼, -버튼 이벤트 추가
- [x] style 추가

**Comment by Sweet-Pumpkin** [comment]
Well done!

**Comment by ulgoon** [comment]
여러분 각자 할 일에 대해 issue를 작성하시고 작업해서 pull request 를 merge 하는 기쁨을 누려보세요:)
